### ISSUE TITLE
The UI scale problem

### ISSUE THREAD

**Issue by zivvc** [PajamaKing/GalvaMod#1]
<img width="1440" alt="WechatIMG31753" src="https://github.com/PajamaKing/GalvaMod/assets/147477128/160747b0-0b6f-4220-b9db-d8f2ee795253">

The ui scale is set to be 100%. However, i still cannot find the button.

**Comment by PajamaKing** [comment]
This is pretty tough to fix, i don't have a steamdeck to test it.
What resolution are you playing at? Does reducing the UI further make the button appear again?

**Comment by PajamaKing** [comment]
Closed by lack of feedback
